### PR TITLE
increased versions

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**

### CODE REVIEW

**Comment by gelisam** [comment]
thanks!

**Comment by BebeSparkelSparkel** [comment]
@gelisam np, could you push this to hackage?

**Comment by gelisam** [comment]
Since this only touches the metadata, I have published [a new revision](http://hackage.haskell.org/package/n-ary-functor-0.1.0.0/revisions/) instead of a new version, is that good enough for your needs?

**Comment by BebeSparkelSparkel** [comment]
yep, thanks!

**Pull request merged**
